#!/bin/bash

# mock of the lxc-stop used to test lxclite on travis due to:
#  https://github.com/travis-ci/travis-ci/issues/1273

if [[ $1 -eq '-dn' && $2 ]]; then
	if [[ -f /tmp/$2 ]]; then
		grep 'started' /tmp/$2 > /dev/null || exit 1 # already started
		echo 'stopped' > /tmp/$2
		exit 0
	else
		exit 1
	fi
fi

exit 1
