#!/bin/bash

# mock of the lxc-create used to test lxclite on travis due to:
#  https://github.com/travis-ci/travis-ci/issues/1273

# lxc-clone <old> <new>
if [[ $1 && $2 ]]; then
	if [[ -d /tmp/lxc/$1 ]]; then
        cp -r /tmp/lxc/$1 /tmp/lxc/$2
        exit 0
	fi
fi

exit 1
