#!/bin/bash

# mock of the lxc-create used to test lxclite on travis due to:
#  https://github.com/travis-ci/travis-ci/issues/1273

# lxc-start -n <container_name>
if [[ $1 -eq '-n' && $2 ]]; then
	if [[ ! -f /tmp/$2 ]]; then
		echo "stopped" > /tmp/$2
		exit 0
	else
		exit 1
	fi
fi

exit 1